
export const PERSONAL_DETAILS_SECTION = "PERSONAL_DETAILS_SECTION";
export const EDUCATION_SECTION = "EDUCATION_SECTION";
export const SKILLS_SECTION = "SKILLS_SECTION";
export const EXPERIENCE_SECTION = "EXPERIENCE_SECTION";
export const HOBBIES_SECTION = "HOBBIES_SECTION";
export const LINKS_SECTION = "LINKS_SECTION";
export const PROJECTS_SECTION = "PROJECTS_SECTION";
export const LINK_SECTION = "LINK_SECTION"
export const ADD_NEW_SECTION = "ADD_NEW_SECTION";